[tool.black]
line-length = 79
exclude = '''
		venv/
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
norecursedirs = ["env/*", "venv/*"]
addopts = "-vv -p no:cacheprovider"
testpaths = "tests/"
python_files = "*_test.py *_tests.py test_*.py"


[tool.isort]
profile = "black"
src_paths = "src"
line_length = 79
multi_line_output = 0
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_between_sections = 1
lines_between_types = 1
known_third_party = ["api", "users", "config", "chat"]
known_standard_library = ["django", "django_filters", "drf_extra_fields", "rest_framework"]