version: '3.3'

services:

  db:
    image: postgres:14
    restart: always
    env_file: ../.env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: andreydogadkin/vink-backend:latest
    restart: always
    env_file: ../.env.prod
    volumes:
      - static_vink:/backend_static/
      - media_vink:/media/
      - logs_vink:/app-backend/.logs/
    command: bash -c "
      python manage.py migrate --noinput
      && python manage.py addmodelsettings
      && python manage.py collectstatic --noinput
      && cp -r /app-backend/static/. /backend_static/static/
      && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    depends_on:
      - db

  redis:
    restart: always
    image: redis:7.2.4
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server

  nginx:
    image: nginx:1.25.0
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_vink:/staticfiles/
      - media_vink:/media/
    depends_on:
      - backend

volumes:
  static_vink:
  media_vink:
  logs_vink:
  pg_data:
  redis_data:
