# Generated by Django 4.2.11 on 2024-04-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YaGptSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "catalog_id",
                    models.CharField(
                        max_length=32, verbose_name="Идентификатор каталога."
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Чем выше значение этого параметра, тем более креативными и случайными будут ответы модели. Принимает значения от 0 (включительно) до 1 (включительно).",
                        verbose_name="Температура",
                    ),
                ),
                (
                    "base_prompt_text",
                    models.TextField(
                        help_text="Позволяет задать контекст запроса и определить поведение модели.",
                        verbose_name="Cистемное сообщение.",
                    ),
                ),
                (
                    "base_error_answer",
                    models.TextField(
                        help_text="Это сообщение будет отправлено пользователю при отсутствии ответа от модели.",
                        verbose_name="Сообщение об ошибке.",
                    ),
                ),
                (
                    "now_active",
                    models.BooleanField(
                        help_text="Активной может быть только одна запись настроек.",
                        verbose_name="Активна.",
                    ),
                ),
                (
                    "context_ttl_seconds",
                    models.PositiveSmallIntegerField(
                        help_text="Количество секунд для хранения контекста в неактивном диалоге.",
                        verbose_name="Время хранения контекста.",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveSmallIntegerField(
                        help_text="Максимальное количество символов в ответе модели.",
                        verbose_name="Символов в ответе.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки модели",
                "verbose_name_plural": "Настройки модели",
            },
        ),
        migrations.AddConstraint(
            model_name="yagptsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("now_active", True)),
                fields=("now_active",),
                name="unique_now_active",
            ),
        ),
    ]
